---
- name: play0
  hosts: all
  tasks:
  - name: create_folders
    file:
      path: /opt/ansible
      state: directory
      mode: '0755'
    become: yes

- name: play1
  hosts: all
  tasks:
  - name: create
    file:
      dest: /opt/ansible/mok1_mnm
      state: touch
    tags:
      - create
    become: yes

- name: play2
  hosts: all:!haproxy_server
  tags:
    -  delete
  tasks:
  - name: delete
    file:
      dest: /opt/ansible//mok1_mnm
      state: absent
    become: yes

- name: play3
  hosts: haproxy_server
  tasks:
  - name: delete
    file:
      dest: /opt/ansible/mok1_mnm
      state: absent
    tags:
      - delete
    become: yes
